### ISSUE TITLE
请问这个仓库是在最新的ET8的基础上改的吗？具体改动是什么呀？

### ISSUE THREAD

**Issue by BelieveXiaoShuai** [FlameskyDexive/ETPlus#1]
另外可以加作者您的联系吗？

**Comment by FlameskyDexive** [comment]
如描述，跟ET master的区别在于，集成EUI（字母歌适配ET的UGUI的UI框架），集成YooAsset资源加载（包含热更下载流程），集成鲁班配置（当前暂未接入，后续可能会接入）。具体demo游戏案例请看我主页的LOH。有问题可以ET大群找我就好，Flamesky
