### ISSUE TITLE
unity单独运行服务器

### ISSUE THREAD

**Issue by QQJoyByte** [FlameskyDexive/ETPlus#5]
![image](https://github.com/FlameskyDexive/ETPlus/assets/8719145/535e43c8-cb62-4728-86a9-19ed8c7e1982)
根据book中的运行指南，单独运行服务器和客服端，打开ServerTools按钮，就报这个错

**Comment by FlameskyDexive** [comment]
单独运行服务器模式，请：
1. unity打开工程，双击vs打开代码
2. 打开ET.sln工程，编译Dotnet项目
3. 切换DotNet.App，运行VS
4. unity按快捷键F6编译代码，运行即可。

**Comment by QQJoyByte** [comment]
![image](https://github.com/FlameskyDexive/ETPlus/assets/8719145/7046d19e-8815-43e2-a259-914687a20fdc)
更新了，暂时没有安装高版本的vs，用rider编译报这个错误；但是不影响dotnet单独运行，不知道是不是运行之前的缓存

**Comment by FlameskyDexive** [comment]
这个是分析器分析客户端代码有部分不符合ET写法，不影响F6编译，后续我修改下。
