### ISSUE TITLE
加载问题

### ISSUE THREAD

**Issue by QQJoyByte** [FlameskyDexive/ETPlus#6]
![image](https://github.com/FlameskyDexive/ETPlus/assets/8719145/cbe624c7-b15a-4b1b-ab1e-dcd14ccc458a)
大佬，这个不是异步加载吗，为什么不用await就return了，是我没看懂还是可能会有bug

**Comment by FlameskyDexive** [comment]
> ![image](https://private-user-images.githubusercontent.com/8719145/325687551-cbe624c7-b15a-4b1b-ab1e-dcd14ccc458a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTU1NDcsIm5iZiI6MTcxNDA5NTI0NywicGF0aCI6Ii84NzE5MTQ1LzMyNTY4NzU1MS1jYmU2MjRjNy1iMTVhLTRiMWItYWIxZS1kY2QxNGNjYzQ1OGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMDEzNDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYyZGZiNjJkMWYzMWJlZWRkNWMzYTRmN2I4NjczOGQ2MDBmNjFmY2U2ZjU5ZWY3ZjRjNDJkMTNhNTE0Yzk2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.86oj7CpJbHcIeOvd84c-0fG5lCps4gEK6NJoMp4tPHA) 大佬，这个不是异步加载吗，为什么不用await就return了，是我没看懂还是可能会有bug

这个是同步加载Sync，异步下载是另一个方法Async结尾，那个异步方法会await，用Sync是为了跟Async区分，这个命名一开始ET默认的也这样，我就保留了，常规同步加载就直接LoadAsset()命名即可。
